// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNP8JvziUZORFf4IcjCOYbsSxGX4qA6Y8',
    appId: '1:709513673291:web:5fe917988f00b563c02bce',
    messagingSenderId: '709513673291',
    projectId: 'ai-travel-assistant-be3bb',
    authDomain: 'ai-travel-assistant-be3bb.firebaseapp.com',
    storageBucket: 'ai-travel-assistant-be3bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHjy4Ldv7AfSdO1y-CLS82tJXQd5LiUAg',
    appId: '1:709513673291:android:2c5dce4e990b51a2c02bce',
    messagingSenderId: '709513673291',
    projectId: 'ai-travel-assistant-be3bb',
    storageBucket: 'ai-travel-assistant-be3bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRWavTHdzsnDth6bjpqkveecxmD3egFDU',
    appId: '1:709513673291:ios:a99ac324c889d55cc02bce',
    messagingSenderId: '709513673291',
    projectId: 'ai-travel-assistant-be3bb',
    storageBucket: 'ai-travel-assistant-be3bb.firebasestorage.app',
    iosBundleId: 'com.example.tourista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRWavTHdzsnDth6bjpqkveecxmD3egFDU',
    appId: '1:709513673291:ios:a99ac324c889d55cc02bce',
    messagingSenderId: '709513673291',
    projectId: 'ai-travel-assistant-be3bb',
    storageBucket: 'ai-travel-assistant-be3bb.firebasestorage.app',
    iosBundleId: 'com.example.tourista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNP8JvziUZORFf4IcjCOYbsSxGX4qA6Y8',
    appId: '1:709513673291:web:f32458c7664cf9edc02bce',
    messagingSenderId: '709513673291',
    projectId: 'ai-travel-assistant-be3bb',
    authDomain: 'ai-travel-assistant-be3bb.firebaseapp.com',
    storageBucket: 'ai-travel-assistant-be3bb.firebasestorage.app',
  );

}